language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: 
        - COMPILER=g++-4.9
      before_install:
        - cat /etc/*-release

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: 
        - COMPILER=g++-5
      before_install:
        - cat /etc/*-release

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: 
        - COMPILER=g++-6
      before_install:
        - cat /etc/*-release
      
    - os: linux
      compiler: clang
      env: 
        - COMPILER=clang++
      before_install:
        - cat /etc/*-release

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: 
        - COMPILER=clang++-3.5
      before_install:
        - cat /etc/*-release

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: 
        - COMPILER=clang++-3.6
      before_install:
        - cat /etc/*-release

    - os: linux
      env:
        - LLVM_VERSION=3.8.0
        - LLVM_OS_VERSION=3.8.0
        - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
        - COMPILER=clang++
        - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
        - CXXFLAGS=-lc++
        - PATH=$HOME/clang-$LLVM_VERSION/bin:$PATH
        - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
      before_install:
       - cat /etc/*-release
       - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
       - mkdir $HOME/clang-$LLVM_VERSION
       - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
       
    - os: osx
      osx_image: beta-xcode6.1
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 
       

    - os: osx
      osx_image: beta-xcode6.2
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

    - os: osx
      osx_image: beta-xcode6.3
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

    - os: osx
      osx_image: xcode7.1
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 
     
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - COMPILER=clang
        - CXXFLAGS=-lstdc++
      before_install:
        - sw_vers 

script:
  - $COMPILER --version
  - cd test 
  - make CXX=$COMPILER 
  - ./unit_tests